- src: https://github.com/robertdebock/ansible-role-update_package_cache
  name: robertdebock.update_package_cache
  version: 2.0.1
- name: robertdebock.core_dependencies
  version: 2.0.0
- name: robertdebock.epel
  version: 3.0.2
- name: geerlingguy.pip
  version: 2.0.0
- name: robertdebock.bootstrap
  version: 5.0.3
- name: robertdebock.update
  version: 3.0.2
- name: robertdebock.users
  version: 5.0.1
- name: robertdebock.firewall
  version: 5.0.1
- name: robertdebock.hostname
  version: 3.0.0
- name: geerlingguy.postfix
  version: 2.0.0
- name: robertdebock.openssl
  version: 2.0.0
- name: nginxinc.nginx
  version: 0.17.2
- name: nginxinc.nginx_config
  version: 0.2.0
- name: robertdebock.cron
  version: 2.0.0
- name: robertdebock.logrotate
  version: 2.0.0
