---
- name: Create directories for gophish.
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  with_items:
    - { path: "{{ gophish_install_destination }}",   user: "{{ gophish_user }}", group: "{{ gophish_user }}", mode: '0755' }
    - { path: "{{ gophish_service_log_directory }}", user: "{{ gophish_user }}", group: "root",               mode: '0770' }

- name: Install dependency packages.
  package:
    name: "{{ gophish_dependencies }}"
    state: present
